// ═══ MENU CONFIGURATION — 7 GROUPES, 205 ITEMS ═══
export const MENU = [
  { id: '_g1', label: 'TABLEAU DE BORD', icon: '◫', group: true },
  { id: 'commandcenter', label: 'Command Center', icon: '🎯', g: 1 },
  { id: 'dashboard', label: 'Dashboard Principal', icon: '◫', g: 1 },
  { id: 'embaucheaz', label: 'Embauche A→Z', icon: '📋', g: 1, external: '/embauche-az.html' },
  { id: 'journal', label: 'Journal Activite', icon: '📋', g: 1 },
  { id: 'notifications', label: 'Notifications', icon: '🔔', g: 1 },
  { id: 'smartalerts', label: 'Smart Alerts', icon: '🔔', g: 1 },
  { id: 'tbdirection', label: 'Tableau Direction', icon: '📊', g: 1 },

  { id: '_g2', label: 'GESTION RH', icon: '◉', group: true },
  { id: 'accidentTravail', label: 'Accident du Travail', icon: '🚑', g: 2 },
  { id: 'contratgen', label: 'Contrats Legaux', icon: '📝', g: 2 },
  { id: 'contratsmenu', label: 'Contrats & Documents', icon: '▣', g: 2 },
  { id: 'dashabsent', label: 'Dash Absenteisme', icon: '📊', g: 2 },
  { id: 'dashrh', label: 'Dashboard RH', icon: '👥', g: 2 },
  { id: 'employees', label: 'Liste Employes', icon: '◉', g: 2 },
  { id: 'formC4', label: 'Formulaire C4', icon: '📋', g: 2 },
  { id: 'gestionabs', label: 'Gestion Absences', icon: '🗓', g: 2 },
  { id: 'interimaires', label: 'Interimaires', icon: '👷', g: 2 },
  { id: 'joursPrestes', label: 'Jours Prestes', icon: '📅', g: 2 },
  { id: 'onboarding', label: 'Onboarding', icon: '🆕', g: 2 },
  { id: 'onboardwizard', label: 'Onboarding Wizard', icon: '🚀', g: 2 },
  { id: 'planifconges', label: 'Planning Conges', icon: '📅', g: 2 },
  { id: 'portailclient', label: 'Portail Client', icon: '🌐', g: 2, roles: ['admin'] },
  { id: 'gestionclients', label: 'Gestion Clients', icon: '👥', g: 2, roles: ['admin'] },
  { id: 'portail', label: 'Portail Employe', icon: '👤', g: 2 },
  { id: 'proceduresrh', label: 'Procedures RH (64)', icon: '📋', g: 2 },
  { id: 'registrepersonnel', label: 'Registre Personnel', icon: '📖', g: 2 },
  { id: 'rh', label: 'RH & Workflows', icon: '◉', g: 2 },
  { id: 'workflowAbs', label: 'Workflow Absences', icon: '🏖', g: 2 },

  { id: '_g3', label: 'PAIE & CALCULS', icon: '💰', group: true },
  { id: 'gestionprimes', label: '57 Primes & Avantages', icon: '🎁', g: 3 },
  { id: 'annexeReglement', label: 'Annexe Reglement', icon: '📜', g: 3 },
  { id: 'avantages', label: 'Avantages & Remuneration', icon: '★', g: 3 },
  { id: 'baremescp', label: 'Baremes CP', icon: '📊', g: 3 },
  { id: 'baremespp', label: 'Baremes PP SPF', icon: '📋', g: 3 },
  { id: 'calcinstant', label: 'Calcul Instantane', icon: '🔁', g: 3 },
  { id: 'calendrier', label: 'Calendrier Social', icon: '📅', g: 3 },
  { id: 'formC131', label: 'Certificat Vacances C131', icon: '🏖', g: 3 },
  { id: 'cloture', label: 'Cloture Mensuelle', icon: '🔄', g: 3 },
  { id: 'comparateur', label: 'Comparateur Salarial', icon: '⚖', g: 3 },
  { id: 'compteIndividuel', label: 'Compte Individuel', icon: '📄', g: 3 },
  { id: 'coutsannuel', label: 'Couts Annuels', icon: '📊', g: 3 },
  { id: 'couttotal', label: 'Cout Total', icon: '💰', g: 3 },
  { id: 'payslip', label: 'Fiches de Paie', icon: '◈', g: 3 },
  { id: 'flexijobs', label: 'Flexi-Jobs', icon: '⚡', g: 3 },
  { id: 'calcmaladie', label: 'Salaire Garanti', icon: '🏥', g: 3 },
  { id: 'simulateurspro', label: 'Simulateurs Pro (41)', icon: '🔬', g: 3 },
  { id: 'salaires', label: 'Salaires & Calculs', icon: '◈', g: 3 },
  { id: 'simembauche', label: 'Simulateur Embauche', icon: '🧮', g: 3 },
  { id: 'simulicenciement', label: 'Simu Licenciement', icon: '⚖️', g: 3 },
  { id: 'simupension', label: 'Simulateur Pension', icon: '🏖', g: 3 },
  { id: 'simutp', label: 'Temps Partiel', icon: '⏱', g: 3 },
  { id: 'soldetoutcompte', label: 'Solde Tout Compte', icon: '📑', g: 3 },
  { id: 'timeline', label: 'Timeline Paie', icon: '📅', g: 3 },
  { id: 'validation', label: 'Validation Pre-Paie', icon: '✅', g: 3 },
  { id: 'vehiculesatn', label: 'Vehicules & ATN', icon: '🚗', g: 3 },
  { id: 'optifiscale', label: 'Opti Fiscale', icon: '💡', g: 3 },

  { id: '_g4', label: 'DECLARATIONS & COMPTABILITE', icon: '◆', group: true },
  { id: 'analytics', label: 'Analytics', icon: '📈', g: 4 },
  { id: 'belcotax281', label: 'Belcotax 281.10 XML', icon: '📊', g: 4 },
  { id: 'budget', label: 'Budget Previsionnel', icon: '💰', g: 4 },
  { id: 'chargessociales', label: 'Charges ONSS', icon: '🏛', g: 4 },
  { id: 'chomagetemporaire', label: 'Chomage Temporaire', icon: '⏸', g: 4 },
  { id: 'batchdecl', label: 'Declarations Batch', icon: '📋', g: 4 },
  { id: 'declarations', label: 'Declarations ONSS/SPF', icon: '📡', g: 4 },
  { id: 'echeancier', label: 'Echeancier Paiements', icon: '💳', g: 4 },
  { id: 'exportbatch', label: 'Export Batch', icon: '📦', g: 4 },
  { id: 'exportcoda', label: 'Export CODA', icon: '🏦', g: 4 },
  { id: 'exportcompta', label: 'Export Comptable', icon: '📤', g: 4 },
  { id: 'exportcomptapro', label: 'Export Compta Pro', icon: '📒', g: 4 },
  { id: 'exportWinbooks', label: 'Export Winbooks/BOB', icon: '📤', g: 4 },
  { id: 'facturation', label: 'Facturation', icon: '🧾', g: 4 },
  { id: 'fiscal', label: 'Fiscal / TVA Listing', icon: '◇', g: 4, roles: ['admin', 'comptable'] },
  { id: 'tvalisting', label: 'TVA Listing Intervat', icon: '📄', g: 4, roles: ['admin', 'comptable'] },
  { id: 'importcsv', label: 'Import CSV', icon: '📥', g: 4 },
  { id: 'onss', label: 'ONSS / Declarations', icon: '◆', g: 4 },
  { id: 'rapports', label: 'Rapports Mensuels', icon: '📊', g: 4 },
  { id: 'regulPP', label: 'Regularisation PP', icon: '📊', g: 4 },
  { id: 'reporting', label: 'Reporting & Export', icon: '▤', g: 4 },
  { id: 'reportingpro', label: 'Reporting Pro', icon: '📊', g: 4 },
  { id: 'sepa', label: 'SEPA Virements', icon: '💳', g: 4 },
  { id: 'auditfiscale', label: 'Piste Audit SPF', icon: '🔍', g: 4 },
  { id: 'rapportsrole', label: 'Rapports par Role', icon: '📈', g: 4 },

  { id: '_g5', label: 'CONCERTATION SOCIALE', icon: '🏛', group: true },
  { id: 'bilansocial', label: 'Bilan Social', icon: '📋', g: 5 },
  { id: 'compteindividuelannuel', label: 'Compte Individuel Annuel', icon: '📄', g: 5 },
  { id: 'ccts', label: 'Conventions CCT', icon: '📜', g: 5 },
  { id: 'delegations', label: 'Delegations Syndicales', icon: '🏛', g: 5 },
  { id: 'delegationsyndicale', label: 'Delegation Syndicale', icon: '🏛', g: 5 },
  { id: 'egalitehf', label: 'Egalite H/F', icon: '⚖️', g: 5 },
  { id: 'electionsociales', label: 'Elections Sociales', icon: '🗳', g: 5 },
  { id: 'formationsec', label: 'Formation & Securite', icon: '🎓', g: 5 },
  { id: 'lanceursalerte', label: "Lanceurs d'Alerte", icon: '🚨', g: 5 },
  { id: 'plandiversite', label: 'Plan Diversite', icon: '🌍', g: 5 },
  { id: 'rapportce', label: 'Rapport Annuel CE', icon: '🏛', g: 5 },
  { id: 'seuilssociaux', label: 'Seuils Sociaux', icon: '📐', g: 5 },
  { id: 'social', label: 'Social & Assurances', icon: '◆', g: 5 },

  { id: '_g6', label: 'COMMERCIAL & PROSPECTS', icon: '🎯', group: true },
  { id: 'checklistclient', label: 'Checklist Client', icon: '✅', g: 6 },
  { id: 'comparatif', label: 'Comparatif Marche', icon: '⚔️', g: 6 },
  { id: 'diagnostic', label: 'Diagnostic Commercial', icon: '🎯', g: 6 },
  { id: 'diagnosticv', label: 'Diagnostic Prospect', icon: '🎯', g: 6 },
  { id: 'gendocsjur', label: 'Docs Juridiques', icon: '📜', g: 6 },
  { id: 'guidecommercial', label: 'Guide Commercial', icon: '📊', g: 6 },
  { id: 'guidefiduciaire', label: 'Guide Fiduciaire', icon: '📖', g: 6 },
  { id: 'fiduciaire', label: 'Hub Fiduciaire', icon: '🏢', g: 6 },
  { id: 'landing', label: 'Page Commerciale', icon: '🌐', g: 6 },
  { id: 'parserConcurrent', label: 'Audit Concurrent', icon: '🔍', g: 6 },
  { id: 'repriseclient', label: 'Reprise Concurrent', icon: '🔄', g: 6 },
  { id: 'legal', label: 'Juridique & Veille', icon: '⚖', g: 6 },

  { id: '_g_mandats', label: 'MANDATS & PRIMES EMPLOI', icon: '🏛', group: true },
  { id: 'settings', label: 'Parametres', icon: '⚙️', g: 7, roles: ['admin'] },
  { id: 'connexionshub', label: 'Hub Connexions H24', icon: '🔗', g: 7 },
  { id: 'mandatonss', label: 'Mandat ONSS/Mahis', icon: '🏛', g: 7 },
  { id: 'belcotaxmandat', label: 'Belcotax — Mandat Fiscal', icon: '📄', g: 7 },
  { id: 'domiciliation', label: 'Domiciliation 5% Ristourne', icon: '💳', g: 7 },
  { id: 'premieremploi', label: '1er–6e Employé Exonération', icon: '🏅', g: 7 },
  { id: 'activabruxelles', label: 'Activa.brussels (N° 829605)', icon: '✅', g: 7 },
  { id: 'art60cpas', label: 'Art. 60 §7 CPAS', icon: '🏢', g: 7 },
  { id: 'impulsion55', label: 'Impulsion 55+ / Jeunes', icon: '💼', g: 7 },
  { id: 'monbee', label: 'MonBEE — deadline 01/06/2026', icon: '⚡', g: 7 },

  { id: '_g7', label: 'ADMINISTRATION', icon: '👑', group: true },
  { id: 'actionsrapides', label: 'Actions Rapides', icon: '⚡', g: 7 },
  { id: 'admin', label: 'Admin', icon: '👑', g: 7 },
  { id: 'backup', label: 'Backup & Restore', icon: '💾', g: 7 },
  { id: 'permissions', label: 'Rôles & Permissions', icon: '🔐', g: 7 },
  { id: 'adminbaremes', label: 'Admin Baremes', icon: '⚙️', g: 7 },
  { id: 'archives', label: 'Archives GED', icon: '🗄', g: 7 },
  { id: 'auditsecuritecode', label: 'Audit Securite Code', icon: '🛡', g: 7 },
  { id: 'audittrail', label: 'Audit Trail', icon: '🔍', g: 7 },
  { id: 'aureussuite', label: 'Aureus IA', icon: '🔷', g: 7 },
  { id: 'autoindex', label: 'Auto-Indexation', icon: '📈', g: 7 },
  { id: 'autopilot', label: 'Autopilot', icon: '🤖', g: 7 },
  { id: 'cgvsaas', label: 'CGV & Contrat SaaS', icon: '📄', g: 7 },
  { id: 'changelog', label: 'Changelog', icon: '📋', g: 7 },
  { id: 'compliance', label: 'Compliance Radar', icon: '🛡', g: 7 },
  { id: 'demodonnees', label: 'Donnees de Demo', icon: '📦', g: 7 },
  { id: 'ged', label: 'GED Documents', icon: '📁', g: 7 },
  { id: 'historique', label: 'Historique Runs', icon: '📊', g: 7 },
  { id: 'integrations', label: 'Integrations', icon: '🔌', g: 7 },
  { id: 'massengine', label: 'Mass Engine', icon: '🏭', g: 7 },
  { id: 'mentionslegales', label: 'Mentions Legales', icon: '📜', g: 7 },
  { id: 'monitoring', label: 'Monitoring', icon: '🖥', g: 7 },
  { id: 'piloteauto', label: 'Pilote Auto Total', icon: '🏎️', g: 7 },
  { id: 'queue', label: 'File Traitement', icon: '📋', g: 7 },
  { id: 'rgpd', label: 'RGPD Compliance', icon: '🔒', g: 7 },
  { id: 'roadmapinfra', label: 'Roadmap Infrastructure', icon: '🗺', g: 7 },
  { id: 'authroles', label: 'Roles & Permissions', icon: '🔐', g: 7 },
  { id: 'securitedata', label: 'Securite Donnees', icon: '🔒', g: 7 },
  { id: 'support', label: 'Support & Tickets', icon: '🎫', g: 7 },
  { id: 'testsuite', label: 'Test Suite', icon: '🧪', g: 7 },
  { id: 'team', label: 'Equipe', icon: '👥', g: 7 },
  { id: 'portalmanager', label: 'Gestion Portails', icon: '🏢', g: 7 },
];

export const GROUPS = MENU.filter(m => m.group);
export const getGroupItems = (gNum) => MENU.filter(m => m.g === gNum && !m.group);

// ═══ INDEX SOUS-SECTIONS — RECHERCHE CONTEXTUELLE ═══
// Permet de taper "ONSS", "Précompte", "CSSS" etc. dans la barre de recherche
// et d'atterrir directement sur la bonne section de la fiche de paie
export const SEARCH_SUBSECTIONS = [
  {
    id: 'payslip',
    anchor: 'section-onss-cotisations',
    icon: '⚡',
    label: 'ONSS & Cotisations',
    sub: 'Fiche de paie — Paramètres légaux',
    keywords: ['onss','cotisation','13,07','25,07','cotisations sociales','securite sociale','travailleur','patronal','ouvrier','108%','rmmmg','co2','majoration'],
  },
  {
    id: 'payslip',
    anchor: 'section-precompte',
    icon: '🧾',
    label: 'Précompte professionnel',
    sub: 'Fiche de paie — Paramètres légaux',
    keywords: ['precompte','précompte','pp','impot','impôt','tranches','taux','26,75','42,80','48,15','53,50','bonus emploi','quotite','quotité','seuil','fiscal','fiscalite','fiscalité'],
  },
  {
    id: 'payslip',
    anchor: 'section-csss',
    icon: '📊',
    label: 'CSSS — Cotisation spéciale SS',
    sub: 'Fiche de paie — Paramètres légaux',
    keywords: ['csss','cotisation speciale','spéciale','cotisation special','revenu imposable','tranche csss','securite sociale speciale'],
  },
  {
    id: 'payslip',
    anchor: 'section-avantages',
    icon: '🎁',
    label: 'Avantages & Frais propres',
    sub: 'Fiche de paie — Paramètres légaux',
    keywords: ['avantages','frais propres','cheques repas','chèques-repas','eco cheques','éco-chèques','ecocheques','forfait bureau','teletravail','télétravail','km voiture','kilometrique','kilométrique','frais','depenses','dépenses','repas','indemnite','indemnité'],
  },
  {
    id: 'payslip',
    anchor: 'section-saisies',
    icon: '⚖️',
    label: 'Saisies sur salaire',
    sub: 'Fiche de paie — Paramètres légaux',
    keywords: ['saisie','saisies','salaire','art 1409','1409','garnish','garnissement','immunite','immunité','enfant','saisie salaire','baremes saisie'],
  },
  {
    id: 'payslip',
    anchor: 'section-af',
    icon: '👶',
    label: 'Allocations familiales',
    sub: 'Fiche de paie — Paramètres légaux',
    keywords: ['allocations familiales','allocation familiale','af','enfant','iriscare','aviq','groeipakket','bruxelles','wallonie','flandre','region','bxl','wal','vl'],
  },
  {
    id: 'payslip',
    anchor: 'section-cp',
    icon: '📋',
    label: 'Barème sectoriel CP',
    sub: 'Fiche de paie — Paramètres légaux',
    keywords: ['bareme','barème','cp','commission paritaire','sectoriel','classe','minimum','minima','secteur','cp 200','cp 111','cp 118','cp 119','cp 124','cp 140','cp 302','cp 330'],
  },
];
