const fs=require('fs');
const lines=fs.readFileSync('app/AureusSocialPro.js','utf8').split('\n');
let idx=-1;
for(let i=0;i<lines.length;i++){if(lines[i].includes("tab==='cumuls'")&&lines[i].includes('<div>')){idx=i;break;}}
if(idx===-1){console.log('NOT FOUND');process.exit(1);}
const scannerUI="      <div style={{padding:16,background:'rgba(198,163,78,.04)',border:'2px dashed rgba(198,163,78,.25)',borderRadius:14,marginBottom:20}}><div style={{fontSize:14,fontWeight:700,color:'#c6a34e',marginBottom:8}}>Scanner IA</div><div style={{fontSize:11,color:'#888',marginBottom:12}}>Uploadez les fiches de paie PDF ou photo.</div><div style={{display:'flex',gap:10,marginBottom:10}}><label style={{flex:1,padding:12,borderRadius:10,border:'1px solid rgba(198,163,78,.2)',background:'#090c16',cursor:'pointer',textAlign:'center',fontSize:12,color:'#c6a34e'}}><input type='file' multiple accept='.pdf,.jpg,.jpeg,.png' onChange={handleFileUpload} style={{display:'none'}}/>{scanFiles.length?scanFiles.length+' fichier(s)':'Cliquez pour selectionner'}</label><button onClick={doScan} disabled={scanning||!scanFiles.length} style={{padding:'12px 24px',borderRadius:10,border:'none',background:scanFiles.length?'#c6a34e':'rgba(198,163,78,.1)',color:scanFiles.length?'#060810':'#555',fontWeight:700,cursor:scanFiles.length?'pointer':'not-allowed'}}>{scanning?'Analyse...':'Analyser avec IA'}</button></div>{scanLog.length>0&&<div style={{maxHeight:150,overflow:'auto',padding:8,background:'#060810',borderRadius:8}}>{scanLog.map((l,i)=><div key={i} style={{fontSize:10,color:l.includes('OK')?'#22c55e':l.includes('Erreur')?'#ef4444':'#888',fontFamily:'monospace'}}>{l}</div>)}</div>}{scanResult&&<div style={{marginTop:8,padding:8,background:'rgba(34,197,94,.05)',borderRadius:8}}><span style={{fontSize:11,color:'#22c55e'}}>{scanResult.count} fiche(s) analysee(s)</span></div>}</div>";
lines.splice(idx+1,0,scannerUI);
fs.writeFileSync('app/AureusSocialPro.js',lines.join('\n'),'utf8');
console.log('UI OK line '+(idx+1));
